on:
  push:
    branches:
      - master
    paths:
      - 'runner/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: summerwind
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Container Image
        working-directory: runner
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag summerwind/actions-runner:latest \
            -f Dockerfile . --push
